### PR TITLE
Test CSV update

### PR DESCRIPTION
**Pull request by fmoissenet**
- #126
- #34

- - -
This change is [Reviewable](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/127)

### CODE REVIEW

**Comment by fmoissenet** [comment]
#2 Bourne et al. checked from original source + update figures and tables

**Comment by fmoissenet** [comment]
@Ipuch could you confirm that you can see and use my pull request "#2 Bourne et al. checked from original source + update figures and tables" ?

**Comment by fmoissenet** [comment]
#3 Chu et al. checked from original source + update figures and tables

**Comment by Ipuch** [comment]
@fmoissenet I confirm I can see your commits, please dont use "#" in commits and comments as it refers to previous PR and issues.

**Comment by Ipuch** [comment]
A list of issues to solve while updating the database:
- #49 
- #52 
- #55
- #58
- #59 only translation with two translations
- #61

**Pull request merged**
