### PR TITLE
Export of the risk in the csv

### PR DESCRIPTION
**Pull request by ANaaim**
Two elements in this PR : 
- Export the risk in the csv 
- Calculate the risk for the euler sequences.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/129)

### CODE REVIEW

**Comment by ANaaim** [comment]
Probably some improvong to do on where are positioned the function. 

I will continue with the export of the correct name of the degree of freedom

**Comment by ANaaim** [comment]
DX pour la modif de code :

1. Label
2. Sense
3. Origin
4. Direction
5. Euler sequence
6. Translations CS
7. TH joint angle

**Review by Ipuch — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/129)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @ANaaim)

___
*[`spartacus/src/row_data.py` line 634 at r1](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/129#-Ntq57NKAl61_REN5ChE:-Ntq57NKAl61_REN5ChF:b-89gwua) ([raw file](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/blob/74486ed085ca5f2ead5a777327c5a5bc566d1891/spartacus/src/row_data.py#L634)):*
> ```Python
>     def quantify_segment_risk(self, type_risk: str):
>         """
>         Quantify the risk of the joint.
> ```

Use D notations D1, D2, D3, D4 ?



_Code quote:_
```Python
Quantify the risk of the joint.
```
___
*[`spartacus/src/row_data.py` line 657 at r1](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/129#-Ntq4WBvBQ8h4G6IQFED:-Ntq4WBvBQ8h4G6IQFEE:b-ir6fut) ([raw file](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/blob/8c5926b3f0bba7380c09fb295baca987de650204/spartacus/src/row_data.py#L657)):*
> ```Python
>                 adapted_euler_seq += self.parent_biomech_sys.medio_lateral_axis.value[0]
> 
>         if supposed_euler_seq.lower()[2] == "x":
> ```

extra documentation 
___
*[`spartacus/src/row_data.py` line 675 at r1](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/129#-Ntq63wU9g2LONpgG7Zm:-Ntq63wU9g2LONpgG7Zn:bl16wc4) ([raw file](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/blob/8c5926b3f0bba7380c09fb295baca987de650204/spartacus/src/row_data.py#L675)):*
> ```Python
>             risk = 1.0
>         else:
>             risk = 0.5
> ```

In file deviation.py

```python
class Deviation
@staticmethod
def euler_sequence(...) -> float

return 

@staticmethod
def label(...) -> float

return 
```



_Suggestion:_
```Python
        if self.is_joint_euler_angle_ISB_with_adaptation_from_segment():
            risk = 1.0
        else:
            risk = 0.5  
```
___
*[`spartacus/src/row_data.py` line 677 at r1](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/129#-Ntq4z4mBr4iUD2lnfcX:-Ntq4z4mBr4iUD2lnfcY:bsq2wye) ([raw file](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/blob/8c5926b3f0bba7380c09fb295baca987de650204/spartacus/src/row_data.py#L677)):*
> ```Python
>             risk = 0.5
> 
>         return risk
> ```

Put this Joint class



_Code quote:_
```Python
    def is_joint_euler_angle_ISB_with_adaptation_from_segment(self):
        raw_euler_seq = self.joint.euler_sequence.value
        supposed_euler_seq = EulerSequence.isb_from_joint_type(self.joint.joint_type).value
        # Z is supposed to be the +mediolat (point right)
        # Y is supposed to be the +inferosup (point up )
        # X is supposed to be the +anteropost (point front)
        adapted_euler_seq = ""
        for charac in supposed_euler_seq.lower()[0:2]:
            # TODO : probably put this in the biomech_sys function
            if charac == "x":
                adapted_euler_seq += self.parent_biomech_sys.anterior_posterior_axis.value[0]
            elif charac == "y":
                adapted_euler_seq += self.parent_biomech_sys.infero_superior_axis.value[0]
            elif charac == "z":
                adapted_euler_seq += self.parent_biomech_sys.medio_lateral_axis.value[0]

        if supposed_euler_seq.lower()[2] == "x":
            adapted_euler_seq += self.child_biomech_sys.anterior_posterior_axis.value[0]
        elif supposed_euler_seq.lower()[2] == "y":
            adapted_euler_seq += self.child_biomech_sys.infero_superior_axis.value[0]
        elif supposed_euler_seq.lower()[2] == "z":
            adapted_euler_seq += self.child_biomech_sys.medio_lateral_axis.value[0]

        adapted_euler_seq.replace("-", "")

        return adapted_euler_seq == raw_euler_seq

    def quantify_joint_risk(self):
        """
        Quantify the risk associated with the joint which is associated to the euler sequences.
        """
        if self.is_joint_euler_angle_ISB_with_adaptation_from_segment():
            risk = 1.0
        else:
            risk = 0.5

        return risk
```
___
*[`spartacus/src/row_data.py` line 724 at r1](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/129#-Ntq4iMA2ONhsu9VxSsq:-Ntq4iMA2ONhsu9VxSsr:baqnhgi) ([raw file](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/blob/8c5926b3f0bba7380c09fb295baca987de650204/spartacus/src/row_data.py#L724)):*
> ```Python
>         risk_joint = self.quantify_joint_risk()
>         total_risk = risk_segments * risk_joint
>         # TODO : detect if this is angle or translation
> ```

Put this in a method `self.total_risk` ?



_Code quote:_
```Python
        risk_segments = self.quantify_segment_risk("rotation")
        risk_joint = self.quantify_joint_risk()
        total_risk = risk_segments * risk_joint
        # TODO : detect if this is angle or translation
```

**Comment by ANaaim** [comment]
*[`spartacus/src/row_data.py` line 724 at r1](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/129#-Ntq4iMA2ONhsu9VxSsq:-NuTouc06i15E67AW1hJ:b-wtuuji) ([raw file](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/blob/8c5926b3f0bba7380c09fb295baca987de650204/spartacus/src/row_data.py#L724)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Put this in a method `self.total_risk` ?
</blockquote></details>

Would it be more coherent to put it in the deviation class ?

**Comment by ANaaim** [comment]
*[`spartacus/src/row_data.py` line 634 at r1](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/129#-Ntq57NKAl61_REN5ChE:-NuTwUSK34ONM03IYW_t:b-7pysup) ([raw file](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/blob/74486ed085ca5f2ead5a777327c5a5bc566d1891/spartacus/src/row_data.py#L634)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Use D notations D1, D2, D3, D4 ?
</blockquote></details>

Everything in the Deviation class as suggested below

**Comment by ANaaim** [comment]
*[`spartacus/src/enums.py` line 303 at r2](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/129#-NuUV3kz3N3w6h-NrWii:-NuUV3kz3N3w6h-NrWij:b-37tr6z) ([raw file](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/blob/ee56392ac9d57802638a6255454587285286fc45/spartacus/src/enums.py#L303)):*
> ```Python
> 
> 
> def isb_legend_rotation(joint_type: JointType) -> (str, str, str):
> ```

Where this should be ?

**Comment by ANaaim** [comment]
*[`spartacus/src/row_data.py` line 657 at r1](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/129#-Ntq4WBvBQ8h4G6IQFED:-NuUVDws8WDk8NbOE4i9:b-896fjx) ([raw file](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/blob/8c5926b3f0bba7380c09fb295baca987de650204/spartacus/src/row_data.py#L657)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

extra documentation
</blockquote></details>

Done

**Comment by ANaaim** [comment]
*[`spartacus/src/row_data.py` line 675 at r1](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/129#-Ntq63wU9g2LONpgG7Zm:-NuUVHAv-xgwg-W-TTh8:b-peiiba) ([raw file](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/blob/8c5926b3f0bba7380c09fb295baca987de650204/spartacus/src/row_data.py#L675)):*
<details><summary><i>Previously, ANaaim (Alexandre Naaim) wrote…</i></summary><blockquote>

deviation.py file added with all the current risk calculated
</blockquote></details>

Risk was changed to confidence

**Review by Ipuch — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/129)* status: all files reviewed, 8 unresolved discussions (waiting on @ANaaim)

___
*[`spartacus/src/deviation.py` line 15 at r2](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/129#-NuZ4nCvC77LFp3VAFqM:-NuZ4nCvC77LFp3VAFqN:b1jrbpe) ([raw file](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/blob/ee56392ac9d57802638a6255454587285286fc45/spartacus/src/deviation.py#L15)):*
> ```Python
> 
>     @staticmethod
>     def confidence_segment_proximal(row_data, type_risk) -> float:
> ```

confidence_segment_proximal(row_data, type_risk: str) -> float:
Parameters
----------------
row_data: RowData
type_risk: str
   "rotation" or "translation"



_Code quote:_
```Python
confidence_segment_proximal(row_data, type_risk) -> float:
```
___
*[`spartacus/src/enums.py` line 303 at r2](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/129#-NuUV3kz3N3w6h-NrWii:-NuZ54EZ82XcFx705X71:bhx7k43) ([raw file](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/blob/ee56392ac9d57802638a6255454587285286fc45/spartacus/src/enums.py#L303)):*
<details><summary><i>Previously, ANaaim (Alexandre Naaim) wrote…</i></summary><blockquote>

Where this should be ?
</blockquote></details>

method of Joint Class
___
*[`spartacus/src/enums.py` line 327 at r2](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/129#-NuZ5J-02WbRX435b0iy:-NuZ5J-02WbRX435b0iz:b-17icq9) ([raw file](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/blob/ee56392ac9d57802638a6255454587285286fc45/spartacus/src/enums.py#L327)):*
> ```Python
> 
> def isb_legend_translation(joint_type: JointType) -> (str, str, str):
>     # TODO : Put correct dof
> ```

raise NotImplemented("TODO")
___
*[`spartacus/src/load.py` line 138 at r2](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/129#-NuZ5boG6_sL0-k5gWBN:-NuZ5boG6_sL0-k5gWBO:b-xkxisv) ([raw file](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/blob/ee56392ac9d57802638a6255454587285286fc45/spartacus/src/load.py#L138)):*
> ```Python
>                 "article",
>                 "joint",
>                 "angle_translation",
> ```

rotation_or_translation
___
*[`spartacus/src/load.py` line 140 at r2](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/129#-NuZ5j-r7BG9rJxQqv_J:-NuZ5j-r7BG9rJxQqv_K:b-6tskhe) ([raw file](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/blob/ee56392ac9d57802638a6255454587285286fc45/spartacus/src/load.py#L140)):*
> ```Python
>                 "angle_translation",
>                 "degree_of_freedom",
>                 "legend",
> ```

biomechanical_dof
___
*[`spartacus/src/load.py` line 143 at r2](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/129#-NuZ69rzEAjwSFySUfxb:-NuZ69rzEAjwSFySUfxc:b-s3ln6k) ([raw file](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/blob/ee56392ac9d57802638a6255454587285286fc45/spartacus/src/load.py#L143)):*
> ```Python
>                 "humeral_motion",
>                 "humerothoracic_angle",
>                 "value",
> ```

 unit (mm), (rad), instead of rotation_or_translation ?
___
*[`spartacus/src/load.py` line 145 at r2](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/129#-NuZ6Qvh8GBWFnQEmWoI:-NuZ6Qvh8GBWFnQEmWoJ:b-mzr2vy) ([raw file](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/blob/ee56392ac9d57802638a6255454587285286fc45/spartacus/src/load.py#L145)):*
> ```Python
>                 "value",
>                 "confidence",
>             ]
> ```

define types of entry while creating the dataframe.
___
*[`spartacus/src/row_data.py` line 764 at r2](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/129#-NuZ8vXR0XGSBxQp6WvQ:-NuZ8vXR0XGSBxQp6WvR:bqtf65f) ([raw file](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/blob/ee56392ac9d57802638a6255454587285286fc45/spartacus/src/row_data.py#L764)):*
> ```Python
>             ]
> 
>         (legend_dof1, legend_dof2, legend_dof3) = isb_legend_rotation(self.joint.joint_type)
> ```

the call of that function might change

**Comment by ANaaim** [comment]
*[`spartacus/src/load.py` line 145 at r2](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/129#-NuZ6Qvh8GBWFnQEmWoI:-NuZFQHX0xKO8UIDevvs:bb6un1j) ([raw file](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/blob/ee56392ac9d57802638a6255454587285286fc45/spartacus/src/load.py#L145)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

define types of entry while creating the dataframe.
</blockquote></details>

Done

**Comment by ANaaim** [comment]
*[`spartacus/src/load.py` line 140 at r2](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/129#-NuZ5j-r7BG9rJxQqv_J:-NuZKMSw1NCVTX11jNGq:bb6un1j) ([raw file](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/blob/ee56392ac9d57802638a6255454587285286fc45/spartacus/src/load.py#L140)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

biomechanical_dof
</blockquote></details>

Done

**Comment by ANaaim** [comment]
As the image above show ==> new name seems ok ==> should be merge

**Review by Ipuch — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/129#-:-NuZc5Lt5MsRhd2ldgSX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
