### PR TITLE
Risk calculation as defined in article

### PR DESCRIPTION
**Pull request by ANaaim**
This change is [Reviewable](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/125)

### CODE REVIEW

**Comment by ANaaim** [comment]
#122

**Comment by ANaaim** [comment]
Strange that black is not working : 
image

**Comment by Ipuch** [comment]
Okay to merge when everything useful is kept :)

**Comment by ANaaim** [comment]
@Ipuch : should be alright still I do not understand why the linted black does not work in github ==> i run the 
```
black -l 120 . 
```

**Review by Ipuch — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/125)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ANaaim)

**Review by Ipuch — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Ipuch/spartacus-shoulder-kinematic-dataset/125#-:-NshpsN2ANC-GEt7AwRI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ANaaim)

**Pull request merged**
